import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&family=Sora:wght@600;700;900&display=swap"
          rel="stylesheet"
        />
      </head>

      <body>
       
        {children}
        <Footer />
      </body>
    </html>
  );
}
